dependencies {
    compileOnly "org.springframework.boot:spring-boot-starter-web"
    compileOnly "org.springframework.boot:spring-boot-starter-validation"
    implementation("org.springdoc:springdoc-openapi-starter-webmvc-ui:$swagger_version")
    api(project(":uliian-framework-components"))
    testImplementation("com.baomidou:mybatis-plus-boot-starter:$mybatis_plus_version")
}