spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  application:
    name: demo
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1/send_message?useSSL=false&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 901206
    hikari:
      idle-timeout: 10000
      maximum-pool-size: 100
      minimum-idle: 3
framework:
  easy-generator:
    time-wait: 1000
    cidr: 10.0.0.0/8
springdoc:
  swagger-ui:
    path: /swagger-ui.html
